spring.application.name=boot
server.port=8088
spring.thymeleaf.cache=false

#DB
#bootdb / bootUser / mysql
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/bootdb?serverTimezone=Asia/Seoul
spring.datasource.username=bootUser
spring.datasource.password=mysql

# JPA 설정
spring.jpa.database=mysql
# ddl-auto=none(default)
# create : 테이블 자동 생성 (기존 테이블이 있다면 삭제하고 재생성)
# create-drop : 테이블 자동 생성 (애플리케이션이 종료될 때 테이블 삭제)
# update : create 와 생성은 동일 (기존 테이블이 있다면, 추가되는 사항만 변경)
# validate : 생성, 수정 안함 (테이블 클래스와 테이블이 정상적으로 매핑이 되는지만 검사)
# 개발단계 : update => test : update & validate => 배포 운영 : none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#git 설정